### ISSUE TITLE
Device unavailable.

### ISSUE THREAD

**Issue by Kevin-Jaspers** [rkokkelk/nl.xseth.wallbox#1]
See image 
![Screenshot_20230330_215318_Homey](https://user-images.githubusercontent.com/129441829/228949155-ed19d085-81dd-4a30-bf93-a9b432725ac5.png)

**Comment by rkokkelk** [comment]
Hi, thanks for mentioning this issue. This should occur only when Homey cannot connect the API or that the device is disconnected. Could you verify that Homey can access the Wallbox API  and that you can control the wallbox via cloud (API) and ensure that it is not using the bluetooth connection.

**Comment by daniniedermann** [comment]
Hi, same Problem on a Homey Pro 23, many thanks for your work!

**Comment by rkokkelk** [comment]
Thanks for the feedback, could you maybe verify whether restarting the app after the device is added resolves the issue.

If not could you share a diagnostic report with me.

**Comment by daniniedermann** [comment]
Hi, thanks for the quick reply! Unfortunately I can not add a device. The app shows the picture from above and I do not get anywhere. I can gladly share the diagnostic report, how do I create one without device? Thanks!

**Comment by daniniedermann** [comment]
e3a6a2bb-cff3-49bf-94d9-790a5cf882f8 ist the Report

**Comment by rkokkelk** [comment]
This issue should now be fixed, a test version can already be installed via:

* https://homey.app/nl-nl/app/nl.xseth.wallbox/Wallbox-Charger/test/

If the issue persist, please feel free to reopen this issue.

**Comment by daniniedermann** [comment]
Yesss, it works perfectly now, many thanks!!!
