### ISSUE TITLE
Super user or admin user

### ISSUE THREAD

**Issue by nhassink** [rkokkelk/nl.xseth.wallbox#21]

**Comment by nhassink** [comment]
It seems you need a super user account to use this app. When using a normal admin account I don’t see my charger. And I can’t use my super user account since this uses Sign in with Apple for authentication (no normal username/password). Is it possible to fix this so also admin accounts can be used?

**Comment by nhassink** [comment]
Fault message is. Cannot read properties of undefined (reading ‘name’)

**Comment by rkokkelk** [comment]
Ah this is because the JSON that is returned from the API differs from that of an super admin. If you are able to do the same things with your app of starting/ stopping chargers, see technical info about it, etc, it should be possible to implement it for this user.

However in order to do so I need insight in the JSON structure of the API calls for normal admin accounts. Unfortunately, I don have access to those so I'm unable to work on it. If you can share the JSON structure, or maybe some temporary access credentials, with me personally I can look into the JSON structure and fix it for you.

**Comment by nhassink** [comment]
How can I give you this JSON structure? Id be happy to provide this but I don’t know how. The homey script version that was made before this app does work, so this might also give some clues? Also if you have a Wallbox yourself it is rather easy to add another account to it (also what I did for the homey admin account) is this also a possibility?

**Comment by rkokkelk** [comment]
I've just saw this functionality of adding users. So I'll delve into that possibility of getting the JSON structures. If I run into any issues and I need you to copy the JSON structure I'll let you know with some additional instructions on how to get it.

**Comment by nhassink** [comment]
Great! Let me know if I can help / test something.

**Comment by nhassink** [comment]
![IMG_7296](https://user-images.githubusercontent.com/24893225/233125839-ad072da2-d328-41af-8663-f2f182910520.png)

**Comment by nhassink** [comment]
Is this something you can easily explain? Otherwise I could also try to look into this issue. I have some homey development experience

**Comment by rkokkelk** [comment]
I think that there is still a similar issue with incorrect names or ID used to generate the devices. If you have any experience could you please run it manually at home and verify the JSON structure that you receive from WallBox API and whether the devices are properly generated from it. This all happens here:

https://github.com/rkokkelk/nl.xseth.wallbox/blob/dceb22990caa4e4830648555297c43060341a45d/drivers/wallbox/driver.js#L58-L79

Any fixes that you find, you can easily  share with me via a pull request.

**Comment by nhassink** [comment]
Will do

**Comment by nhassink** [comment]
Should be solved by changing line 81 of driver.js from return chargerDevices to return chargerDevices.flat()
Maybe easier than a pull request.

**Comment by rkokkelk** [comment]
Thank you for your info, I've just published a new version for testing with your fix on it. Could you verify whether it works as expected, if so I'll fully publish it.

* https://homey.app/a/nl.xseth.wallbox/test/

**Comment by nhassink** [comment]
Works

**Comment by rkokkelk** [comment]
Fixed in 90730112584c261dd81d84f307f4c522b8827bff
