### ISSUE TITLE
Error Cannot read property of undefined (reading log)

### ISSUE THREAD

**Issue by kringloper** [rkokkelk/nl.xseth.wallbox#23]
Get this message  (0.2.0) when trying to add a second device to Homey (we use two different accounts for two different cars to seperate sessions | payments).

In the previous version it gave a message 'no new device found'. Tried this again in this version to find out if adding a second device/account is now possible.

**Comment by rkokkelk** [comment]
This seem as two different bugs, mainly that adding new devices no longer works.

@kringloper before version `0.2.0` it should already be possible to add new devices (charging stations). Could you make a separate issue for that.

**Comment by roelvdberge** [comment]
I have this bug too. Just installed the app and tried to add my first (and only) device.

**Comment by rkokkelk** [comment]
This issue should be fixed in version `0.2.1` which is currently under review. Should be made available in the next couple of days. If you can't wait you can try install the test version from the following link:

* https://homey.app/a/nl.xseth.wallbox/test/
