### ISSUE TITLE
404 message

### ISSUE THREAD

**Issue by Designburo** [rkokkelk/nl.xseth.wallbox#26]
When used lock unlock I get directly a 404 message.
If I unlock with the wallbox app and start charging, then the consumption information does show up in the homey wallbox app. Used hp2023.

**Comment by puppuw** [comment]
Same for me

**Comment by nhassink** [comment]
Same here, maybe a change in the Wallbox api?

**Comment by Designburo** [comment]
> Same here, maybe a change in the Wallbox api?

No that is not the case as far as I looked. The script i first wrote for homey still works, so it doesn't look like changes in the API.

**Comment by rkokkelk** [comment]
So basically checked the difference between the app and the script and basically these both use the exact same URLs and functionality. So I don't really get the difference in returns. 

@Designburo could you verify that running the app and the script result in different return codes when using in the same scenario. E.g. when a car is plugged or unplugged. 

Can the rest verify that the changing of Amps during charging does work. This basically use the same underlying functions and APIs so I was wondering whether that functionality does or does not work.

**Comment by rkokkelk** [comment]
Okay so found a type in the generation of the URL, so basically I found the bug and will release it soon.

**Comment by rkokkelk** [comment]
The fix is included in version `0.2.3` and that should be live now.

**Comment by Designburo** [comment]
> @Designburo could you verify that running the app and the script result in different return codes when using in the same scenario. E.g. when a car is plugged or unplugged.

Sorry. For some reason I never get gitHub notifications, so I just now noticed your question. Luckily you found the issue! Thanks!
