### ISSUE TITLE
Homey Pro Wallbox Charger cycling in and out if connectivety

### ISSUE THREAD

**Issue by steinaan** [rkokkelk/nl.xseth.wallbox#28]
The Homey Pro Wallbox Charger app cycles in and out of contact with the charger  in my Homey Pro unit. WiFi signal is very good. How can this be rectified in an upcoming release?

**Comment by jmpetrucci** [comment]
I have the same. When I add my wallbox is fully operational for couple of seconds, after that I got message device is unavailable and cannot see anything about the Wallbox. Is there a special user to create to manage this?

**Comment by rkokkelk** [comment]
Does this issue still consists with the latest version of the app?
