### ISSUE TITLE
Apparaat Onbeschikbaar

### ISSUE THREAD

**Issue by BerndGaykema** [rkokkelk/nl.xseth.wallbox#31]
Hoi,

Een mooie app, heel nuttig voor mijn Homey - Sessy - WallBox koppeling!
Dank daarvoor.

Het werkt vaak voor langere periodes prima met mijn WallBox Pulsar Plus.
Maar soms is de WallBox ineens onbereikbaar geworden.
Is dit een probleem van WallBox of van Homey?
Als ik gewoon inlog op de statuspagina van mijnwallbox krijg ik direct verbinding. De API-request levert echter niets op.
Zie bijgevoegde foto met de error melding.
![WallBox_Homey_Error](https://github.com/rkokkelk/nl.xseth.wallbox/assets/35397216/d5b0e4df-721a-4766-8346-1bcef96b86d4)

**Comment by rkokkelk** [comment]
Hi, bedankt voor je feedback. Ik heb een idee waardoor het kan komen en ik zal binnenkort een nieuwe versie publiceren die het moet verhelpen.

**Comment by BerndGaykema** [comment]
Nog even wat extra informatie:
- Als ik de app opnieuw opstart werkt deze direct weer goed.
- Het lijkt erop dat de app zich verslikt als de Power Booster zijn werk doet. Wanneer bij mij thuis de inductieplaat aangaat reduceert de WallBox het vermogen naar de auto, of schakelt deze zelfs tijdelijk naar 0 kW (laden stopt). Wanneer er weer ruimte is gaat de WallBox weer laden (minimaal 6A is nodig). Vandaag was dat het geval en crashte de app.

**Comment by sylvaink69** [comment]
Hier identiek hetzelfde probleem. Zonder dat er een inductieplaat of een andere grootverbruiker in dienst was.

**Comment by BerndGaykema** [comment]
Ik heb het probleem omzeild door iedere nacht de WallBox-app te herstarten. Dit heb ik in een flow verwerkt (als tijd = 04:00 uur, herstart app Wallbox). Sindsdien werkt alles uitstekend.

**Comment by BerndGaykema** [comment]
Ik heb de test-app geïnstalleerd (0.3.0) en ga deze de komende dagen monitoren.
De dagelijkse reset heb ik uitgeschakeld.

Dank voor de moeite Roy !
