### ISSUE TITLE
Sign in with Apple ID

### ISSUE THREAD

**Issue by lmeijer66** [rkokkelk/nl.xseth.wallbox#33]
Unfortunately I cannot use the Wallbox app for the HomeyPro (yet), because I sign into Wallbox with my Apple ID. Will this be supported in the (near) future? Thanks!!😊

**Comment by rkokkelk** [comment]
Implementing any other authentication method using SSO methodologies is quite complex. Also I think there is a very small target group for this, so I've got no plan to implement this..
