### ISSUE TITLE
Apparaat fout

### ISSUE THREAD

**Issue by Barney1977** [rkokkelk/nl.xseth.wallbox#34]
Sinds enkele dagen staat Wallbox met een rood driehoekje weergegeven. En is status onbereikbaar. Apparaat al keer opnieuw aangemaakt zonder resultaat.

**Comment by rkokkelk** [comment]
Kan je de wallbox nog wel bedienen via de wallbox App. Zo niet dan kan het ook aan de internet connectiviteit liggen van je wallbox zelf.

Is dit wel het geval, maak nieuw apparaat aan. Wacht 5m en verstuur dan diagnoserapport via Homey en deel mij de id. Dan zal ik ernaar kijken.

**Comment by Barney1977** [comment]
Dank,Lijkt idd in wifi van wallbox te zitten. Na volledig spanningsloos maken is verbinding hersteld. Met vriendelijke groet, Henk van Barneveld   Op 22 mrt 2024 om 23:41 heeft RoyK ***@***.***> het volgende geschreven:﻿
Kan je de wallbox nog wel bedienen via de wallbox App. Zo niet dan kan het ook aan de internet connectiviteit liggen van je wallbox zelf.
Is dit wel het geval, maak nieuw apparaat aan. Wacht 5m en verstuur dan diagnoserapport via Homey en deel mij de id. Dan zal ik ernaar kijken.
