### ISSUE TITLE
Possibility to see if car is connected but fully charged

### ISSUE THREAD

**Issue by FredV1904** [rkokkelk/nl.xseth.wallbox#36]
Hello There,

With Homey I check every 5 minutes if there has been sufficient solar production on averag over the last 5 minutes. If there has been enough production I activate (if not activated yet) the charging of the Wallbox and I set the power (in Amps) calculated from the solar production measured. It then charges at that power.
Sometimes the car is fully charged and the script still runs and changes the Amps although it serves no purpose as the car is charged. Doing that a few times often makes the wallbox stop responding (don't know why).

Is there a way (status)  to see if the car is connected (that works) but does not require power? I see there is a status (Connected, waiting for car) but I can't seem to test on it in the scripts.

**Comment by rkokkelk** [comment]
The connected, waiting for car is used for this. This is the only information I get from Wallbox so I cannot elaborate on this further unfortunately.
